### PR TITLE
Babel plugin for extracting ReactSpecimen source as text

### LINKED ISSUE #284: React Element stringification doesn't work well
Problem: If we use actual React Elements (instead of JSX strings) in ReactSpecimens, the output can be unpredictable.

In:

```jsx
<ReactSpecimen>
  <MyComponent />
</ReactSpecimen>
```

Out (in the ReactSpecimen's source view):

```
<>
```

This happens because of minification and production optimizations like [babel-plugin-transform-react-constant-elements](https://babeljs.io/docs/plugins/transform-react-constant-elements/).

Apart from the optimization-related problems, the output also breaks/doesn't look good when we have functions, React components or non-trivial types (e.g. Immutable.Map) as props.

### PR DESCRIPTION
**Pull request by jstcki**
Fixes #284

### CODE REVIEW

**Comment by herrstucki** [comment]
Needs tests.

File: src/babel/reactspecimen-source.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+          );
+
+          attributes.push(
+            t.jSXAttribute(
+              t.jSXIdentifier('sourceText'),
+              t.jSXExpressionContainer(
+                t.stringLiteral(stripIndent(sourceText).trim())
+              )
+            )
+          );
```
Comment (wereHamster) [inline src/babel/reactspecimen-source.js]: You should use `path.replaceWith(…)` instead of modifying `attributes`.
