### PR TITLE
Fix path configuration

### LINKED ISSUE #265: Is `path` a required option on all levels now?
I just tried to upgrade from Catalog `2.4.0` to `2.5.0.beta7` and got an error because I did not define `path` on every level of the config. I had something like this (taken from Catalog's current online documentation):

    Catalog.render({
      title: 'My Catalog',
      // NOTE: No `path` field on this level
      pages: [
        {
          path: '/',             // The path where the page can be accessed
          title: 'Introduction', // The page title
          src: 'docs/intro.md'   // Path to the Markdown document
        },
        // Other pages …
      ]
    }, document.getElementById('catalog'));

If I add a `path` field to the top level (i.e. right after `title: 'My Catalog'`) it works. I got the hint that I need to do this from Catalog's own config on its website.

My questions now are the following:

1. Was this breakage introduced accidentally?
2. If it was introduced consciously: what is the reason for it (because the path you have to specify there will never actually be seen)
3. If it was a conscious decision: do we really want this?

### PR DESCRIPTION
**Pull request by herrstucki**
For page groups, the `path` property is unnecessary but Catalog would fail when not provided (regression in 2.5.0).

Fixes #265

### CODE REVIEW

File: src/configure.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ export default (config) => {
         ...page,
         id: ++pageId,
         // Currently, catalog can't be nested inside other page routes, it messes up <Link> matching. Use `basePath`
-        path: parsePath(page.path || page.name, {basePath}).pathname,
+        path: page.pages ? null : parsePath(page.path || page.name, {basePath}).pathname,
```
Comment (naehrstoff) [inline src/configure.js]: I like this behavior: if `pages` are defined it really doesn't make sense to have a `path`, so explicitely setting it to `null` (even if it were available) is a good choice.

**Comment by naehrstoff** [comment]
Thank you, this looks good to me!

**Comment by herrstucki** [comment]
@naehrstoff released in v2.5.3 :v:
