### PR TITLE
Fix specimen body parsing

### LINKED ISSUE #95: Crash when code block contains what looks like valid YAML
I have the following text in my markdown file:

````
    ```code|lang-js
    const stringAndNumber: Tuple2<string,number> = mkTuple2("string", 42);
    ```
````

The specimen body parser parses the text as a YAML block and empty/undefined children. Later React emits this warning:

```
Warning: Failed propType: Required prop `children` was not specified in `Code`.
Check the render method of `SpecimenContainer`.
```

I'll prepare a pull request once I finish writing this documentation.

### PR DESCRIPTION
**Pull request by herrstucki**
Before, any Specimen body which contained valid YAML was parsed. That meant also something like `const foo:Bar = 3;` or `<div style={{fontSize: 30}}>foo</div>` was parsed (because of the `:`)!

This PR introduces two changes to this logic:

1. Specimens which only need YAML (e.g. ColorSpecimen), now use a function which only does that
2. Specimens which contain primarily non-YAML content (e.g. CodeSpecimen) now won't attempt to parse any YAML *unless* they contain a frontmatter-like section separated with `---`. This is similar to before but it's a) *opt-in* for specific specimens and b) *only* content before `---` (if present) will be attempted to be parsed.

Fixes #95. Pinging @wereHamster who reported this.

### CODE REVIEW

File: src/utils/parseSpecimenBody.js [hunk 1]
```diff
@@ -4,39 +4,32 @@ const yamlOptions = {schema: CORE_SCHEMA};
...
-      text.charAt(i) === C_DASH &&
-      text.charAt(i + 1) === C_DASH &&
-      text.charAt(i + 2) === C_DASH &&
-      text.charAt(i + 3) === C_NEWLINE
-    ) {
-      return [text.slice(0, i), text.slice(i + 4)];
-    }
-  }
-  return [text];
+const SPLITTER = '---\n';
```
Comment (wereHamster) [inline src/utils/parseSpecimenBody.js]: Shouldn't this be `'\n---\n`? Otherwise it will match any line which ends with `---`, even if there are characters before it.

Comment (herrstucki) [inline src/utils/parseSpecimenBody.js]: Yes but then we need to also check if the string starts with `---\n`.

**Comment by herrstucki** [comment]
@wereHamster I improved the splitting and added a test for the case where a line ends but doesn't start with `---\n`
